/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package javaapplication2;

/**
 *
 * @author user
 */
///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
// */
//package com.mycompany.main;

/**
 *
 * @author user
 */
import javax.swing.*;
 import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class first extends javax.swing.JFrame {

    /**
     * Creates new form first
     */
    public first() {
        new future();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(first.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }

    // Variables declaration - do not modify                     
    // End of variables declaration                   
}
class future implements ActionListener {
    JFrame first;
    public future()
    {
        first =new JFrame("first");
        first.setVisible(true);
        first.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        first.setSize(500,500);
        first.setLayout(null);
          JLabel l1 = new JLabel("Membership annual subscription");
          JLabel l2 = new JLabel("Description");
          JLabel l3 = new JLabel("Our goals from this application are" ) ;
          JLabel l4 = new JLabel("that we serve the customer " ) ;
          JLabel l5 = new JLabel("so that he gets faster and better service" ) ;
          JLabel l6 = new JLabel("Best wishes" ) ;
          JLabel l7 = new JLabel("Advantages and offers" ) ;
          JLabel l8 = new JLabel("If you subscribe more than 5 you get " ) ;
          JLabel l9 = new JLabel("5% discount from the annual subscribe " ) ;
          JLabel l10 = new JLabel("Please choose which number to subscribe");
          JButton b1 =new JButton("one");
          JButton b2 = new JButton("more");

        l1.setBounds(150,5,250,30);
        l2.setBounds(10,45,100,30);
        l3.setBounds(15,75,250,30);
        l4.setBounds(15,105,250,30);
        l5.setBounds(15,135,250,30);
        l6.setBounds(15,165,250,30);
        l7.setBounds(10,240,250,30);
        l8.setBounds(15,270,250,30);
        l9.setBounds(15,300,250,30);
        l10.setBounds(10,350,260,30);
        b1.setBounds(50,390,75,25);
        b2.setBounds(150,390,75,25);
        b1.setBackground(Color.decode("#B04759"));
        b2.setBackground(Color.decode("#B04759"));
        b1.setForeground(Color.white);
        b2.setForeground(Color.white);
        first.add(l1);        first.add(l2);
        first.add(l3);        first.add(l4);
        first.add(l5);        first.add(l6);
        first.add(l7);        first.add(l8);
        first.add(l9);        first.add(l10);
        first.add(b1);
        first.add(b2);
        b2.addActionListener(this);
        b1.addActionListener(this);
        first.getContentPane().setBackground(Color.decode("#F99B7D"));
        first.setResizable(false);
        


    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("more")) {
            {
                more m = new more();
                first.dispose();
                    
            }
        }
        else if (e.getActionCommand().equals("one")) {
            createFrame1();
            first.dispose();
        }
    }
    
    
    

    
    
    ///create frame one
    private static void createFrame1() {
        JFrame frame1 = new JFrame("Frame 1");
        frame1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame1.setSize(300, 200);
        frame1.setLayout(new FlowLayout());

        JRadioButton maleRadioButton = new JRadioButton("Male");
        JRadioButton femaleRadioButton = new JRadioButton("Female");
        ButtonGroup group = new ButtonGroup();    
        JButton submitButton = new JButton("Submit");
        
        frame1.getContentPane().setBackground(Color.decode("#F99B7D"));
        frame1.setResizable(false);
        submitButton.setBackground(Color.decode("#B04759"));
        submitButton.setForeground(Color.white);
        maleRadioButton.setBackground(Color.decode("#B04759"));
        maleRadioButton.setForeground(Color.white);
        femaleRadioButton.setBackground(Color.decode("#B04759"));
        femaleRadioButton.setForeground(Color.white);

        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (maleRadioButton.isSelected()) {
                    frame1.setVisible(false);
                    createFrame2();
                    frame1.dispose();
                }else if(femaleRadioButton.isSelected()){
                    frame1.setVisible(false);
                    createFrame3();
                    frame1.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(frame1, "Please select a gender.");
                }
            }
        });

        frame1.add(maleRadioButton);
        frame1.add(femaleRadioButton);
        group.add(maleRadioButton);
        group.add(femaleRadioButton);
        frame1.add(submitButton);
        frame1.setVisible(true);
    }

    
    ///create frame age
    private static void createFrame2() {
        JFrame frame2 = new JFrame("Frame 2");
        frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame2.setSize(300, 200);
        frame2.setLayout(new FlowLayout());

        JButton button1 = new JButton("4:15");
        JButton button2 = new JButton("15:35");
        JButton button3 = new JButton("35:60");

        frame2.add(button1);
        frame2.add(button2);
        frame2.add(button3);
        
        
        
        frame2.getContentPane().setBackground(Color.decode("#F99B7D"));
        frame2.setResizable(false);
        button1.setBackground(Color.decode("#B04759"));
        button2.setBackground(Color.decode("#B04759"));
        button1.setForeground(Color.white);
        button2.setForeground(Color.white);
        button3.setBackground(Color.decode("#B04759"));
        button3.setForeground(Color.white);
        
        
        
        button1.addActionListener(new ActionListener(){
        
                @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == button1){
                    male1 f = new male1();
                    frame2.dispose();
                }
            }
        
        
        });
        
        
        button2.addActionListener(new ActionListener(){
        
                @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == button2){
                    male2 f = new male2();
                    frame2.dispose();
                }
            }
        
        
        });
        
        
        
        
        button3.addActionListener(new ActionListener(){
        
                @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == button3){
                    male3 f = new male3();
                    frame2.dispose();
                }
            }
        
        
        });
        
        
        
        

        frame2.setVisible(true);
    }
    
    
    
    ///create frame age for female
    private static void createFrame3() {
        JFrame frame2 = new JFrame("Frame 2");
        frame2.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame2.setSize(300, 200);
        frame2.setLayout(new FlowLayout());

        JButton button1 = new JButton("4:15");
        JButton button2 = new JButton("15:35");
        JButton button3 = new JButton("35:60");

        frame2.add(button1);
        frame2.add(button2);
        frame2.add(button3);
        
        frame2.getContentPane().setBackground(Color.decode("#F99B7D"));
        frame2.setResizable(false);
        button1.setBackground(Color.decode("#B04759"));
        button2.setBackground(Color.decode("#B04759"));
        button1.setForeground(Color.white);
        button2.setForeground(Color.white);
        button3.setBackground(Color.decode("#B04759"));
        button3.setForeground(Color.white);
        
        button1.addActionListener(new ActionListener(){
        
                @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == button1){
                    female1 f = new female1();
                    frame2.dispose();
                }
            }
        
        
        });
        
        
        button2.addActionListener(new ActionListener(){
        
                @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == button2){
                    female2 f = new female2();
                    frame2.dispose();
                }
            }
        
        
        });
        
        
        
        
        button3.addActionListener(new ActionListener(){
        
                @Override
            public void actionPerformed(ActionEvent e) {
                if(e.getSource() == button3){
                    female3 f = new female3();
                    frame2.dispose();
                }
            }
        
        
        });

        frame2.setVisible(true);
    }
}



